#!/usr/bin/env python

from sys import argv


def main():
    print(f"#args = {len(argv) - 1}")
    for index, arg in enumerate(argv[1:], 1):
        print(f"arg[{index}] = {arg!r}")


if __name__ == "__main__":
    main()
